### PR TITLE
Add tab for disease-related relative risks

### PR DESCRIPTION
**Pull request by f-hafner**
- Add `relative_risk_module`
- add filtering logic inside the main app: depending on the selected diseases and risk factors, different relative risks are selected and passed on to the relative risk module.
- add some more functions in utils, some of them tested

The reactivity is such that when the user changes anything in the diseases or risk factors tab, the selection in the relative risks tab is completely reset. Making this more user-friendly and only re-setting based on the *delta* of the selected items would require a little more thought and work.

To do
- [x] add test that server-side tests
- [x] add test for `filter_relative_risks`?
- [x] expand to relative risks for risk factor -> death and risk factor -> disability? 

Update
- return single dataframe of selected relative risk files, including `to` and `from` columns
- capitalized heading

### CODE REVIEW

**Comment by maltelueken** [comment]
Looks nice! It also works well when removing a disease or risk factor involved in the relative risk. Regarding output, it would be nice if also the `from` and `to` of the relative risk is returned. Also, we don't need to separate relative risks from risk factors and diseases in the output.

The heading should be capitalized -> `Relative Risks`.

**Comment by maltelueken** [comment]
After talking to Hendriek: There should also be options to select relative risks for death and disability for each risk factor.

**Comment by f-hafner** [comment]
I added the things as you requested, added tests and made the code more readable.

**Review by maltelueken — APPROVED** [review]
This looks good and everything works as expected. Maybe squash some of the commits, otherwise this can be merged.

One general remark: `bslib` is currently not in our dependencies list, we should probably add that.

**Comment by f-hafner** [comment]
I added `bslib` to DESCRIPTION

**Pull request merged**
