### PR TITLE
Add basic scenario tab

### PR DESCRIPTION
**Pull request by f-hafner**
Adds a simple scenario tab and deprecates #34 

Adds simple functionality for creating scenarios.
- user can add multiple scenarios
- user can remove the last scenario (sequentially)

If you think there's a need to add some tests, let me know.

### CODE REVIEW

**Comment by f-hafner** [comment]
how do you load it? it works fine for me with `load_all(); launch_application()`. but I'm getting errors when doing `devtools::install(); hiaR::launch_application()`. let's check tomorrow.

**Comment by f-hafner** [comment]
the problem with `devtools::install()` is in #37

**Comment by f-hafner** [comment]
the last two commits fix #37

**Review by maltelueken — APPROVED** [review]
Looks good!

**Pull request merged**
